// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse.Fulfillment.DBModel;

#nullable disable

namespace Warehouse.Fulfillment.DBModel.Migrations
{
    [DbContext(typeof(FulfillmentDbContext))]
    [Migration("20260419194329_AddProductPricesAndSoCurrency")]
    partial class AddProductPricesAndSoCurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TrackingUrlTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Carriers_Code");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Carriers_Name");

                    b.ToTable("Carriers", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.CarrierServiceLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BaseRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("EstimatedDeliveryDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("PerKgRate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId")
                        .HasDatabaseName("IX_CarrierServiceLevels_CarrierId");

                    b.HasIndex("CarrierId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_CarrierServiceLevels_CarrierId_Code");

                    b.ToTable("CarrierServiceLevels", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.CustomerReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("ConfirmedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReceivedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("ReceivedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ReturnNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_CustomerReturns_CreatedAtUtc");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_CustomerReturns_CustomerId");

                    b.HasIndex("ReturnNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerReturns_ReturnNumber");

                    b.HasIndex("SalesOrderId")
                        .HasDatabaseName("IX_CustomerReturns_SalesOrderId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CustomerReturns_Status");

                    b.ToTable("CustomerReturns", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.CustomerReturnLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerReturnId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerReturnId")
                        .HasDatabaseName("IX_CustomerReturnLines_CustomerReturnId");

                    b.ToTable("CustomerReturnLines", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.FulfillmentEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_FulfillmentEvents_EventType");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_FulfillmentEvents_OccurredAtUtc");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_FulfillmentEvents_EntityType_EntityId");

                    b.ToTable("FulfillmentEvents", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ParcelNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParcelNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Parcels_ParcelNumber");

                    b.HasIndex("SalesOrderId")
                        .HasDatabaseName("IX_Parcels_SalesOrderId");

                    b.ToTable("Parcels", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.ParcelItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ParcelId")
                        .HasColumnType("int");

                    b.Property<int>("PickListLineId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("IX_ParcelItems_ParcelId");

                    b.HasIndex("PickListLineId")
                        .HasDatabaseName("IX_ParcelItems_PickListLineId");

                    b.ToTable("ParcelItems", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.PickList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("PickListNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_PickLists_CreatedAtUtc");

                    b.HasIndex("PickListNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_PickLists_PickListNumber");

                    b.HasIndex("SalesOrderId")
                        .HasDatabaseName("IX_PickLists_SalesOrderId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PickLists_Status");

                    b.ToTable("PickLists", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.PickListLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("PickListId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PickedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("PickedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SalesOrderLineId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PickListId")
                        .HasDatabaseName("IX_PickListLines_PickListId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_PickListLines_ProductId");

                    b.HasIndex("SalesOrderLineId")
                        .HasDatabaseName("IX_PickListLines_SalesOrderLineId");

                    b.ToTable("PickListLines", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.ProductPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "CurrencyCode", "ValidFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductPrices_ProductId_CurrencyCode_ValidFrom");

                    b.HasIndex("ProductId", "CurrencyCode", "ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_ProductPrices_ProductId_CurrencyCode_ValidFrom_ValidTo");

                    b.ToTable("ProductPrices", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int");

                    b.Property<int?>("CarrierServiceLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("CompletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("ConfirmedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("CustomerAccountId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("RequestedShipDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ShippedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingCountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingStateProvince")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingStreetLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShippingStreetLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Draft");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("CarrierServiceLevelId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_SalesOrders_CreatedAtUtc");

                    b.HasIndex("CustomerAccountId")
                        .HasDatabaseName("IX_SalesOrders_CustomerAccountId");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_SalesOrders_CustomerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_SalesOrders_OrderNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SalesOrders_Status");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_SalesOrders_WarehouseId");

                    b.ToTable("SalesOrders", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.SalesOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("OrderedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PackedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PickedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_SalesOrderLines_ProductId");

                    b.HasIndex("SalesOrderId")
                        .HasDatabaseName("IX_SalesOrderLines_SalesOrderId");

                    b.HasIndex("SalesOrderId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_SalesOrderLines_SOId_ProductId");

                    b.ToTable("SalesOrderLines", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int");

                    b.Property<int?>("CarrierServiceLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DispatchedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("DispatchedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingCountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingStateProvince")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingStreetLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShippingStreetLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Dispatched");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrackingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId")
                        .HasDatabaseName("IX_Shipments_CarrierId");

                    b.HasIndex("CarrierServiceLevelId");

                    b.HasIndex("DispatchedAtUtc")
                        .HasDatabaseName("IX_Shipments_DispatchedAtUtc");

                    b.HasIndex("SalesOrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Shipments_SalesOrderId");

                    b.HasIndex("ShipmentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Shipments_ShipmentNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Shipments_Status");

                    b.ToTable("Shipments", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.ShipmentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SalesOrderLineId")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderLineId");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("IX_ShipmentLines_ShipmentId");

                    b.ToTable("ShipmentLines", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.ShipmentTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("IX_ShipmentTrackingEntries_ShipmentId");

                    b.ToTable("ShipmentTrackingEntries", "fulfillment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.CarrierServiceLevel", b =>
                {
                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.Carrier", "Carrier")
                        .WithMany("ServiceLevels")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.CustomerReturn", b =>
                {
                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.SalesOrder", "SalesOrder")
                        .WithMany()
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.CustomerReturnLine", b =>
                {
                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.CustomerReturn", "CustomerReturn")
                        .WithMany("Lines")
                        .HasForeignKey("CustomerReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerReturn");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.Parcel", b =>
                {
                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.SalesOrder", "SalesOrder")
                        .WithMany("Parcels")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.ParcelItem", b =>
                {
                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.Parcel", "Parcel")
                        .WithMany("Items")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.PickListLine", "PickListLine")
                        .WithMany()
                        .HasForeignKey("PickListLineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Parcel");

                    b.Navigation("PickListLine");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.PickList", b =>
                {
                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.SalesOrder", "SalesOrder")
                        .WithMany("PickLists")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.PickListLine", b =>
                {
                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.PickList", "PickList")
                        .WithMany("Lines")
                        .HasForeignKey("PickListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.SalesOrderLine", "SalesOrderLine")
                        .WithMany()
                        .HasForeignKey("SalesOrderLineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PickList");

                    b.Navigation("SalesOrderLine");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.SalesOrder", b =>
                {
                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.CarrierServiceLevel", "CarrierServiceLevel")
                        .WithMany()
                        .HasForeignKey("CarrierServiceLevelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Carrier");

                    b.Navigation("CarrierServiceLevel");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.SalesOrderLine", b =>
                {
                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.SalesOrder", "SalesOrder")
                        .WithMany("Lines")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.Shipment", b =>
                {
                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.CarrierServiceLevel", "CarrierServiceLevel")
                        .WithMany()
                        .HasForeignKey("CarrierServiceLevelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.SalesOrder", "SalesOrder")
                        .WithMany()
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Carrier");

                    b.Navigation("CarrierServiceLevel");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.ShipmentLine", b =>
                {
                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.SalesOrderLine", "SalesOrderLine")
                        .WithMany()
                        .HasForeignKey("SalesOrderLineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.Shipment", "Shipment")
                        .WithMany("Lines")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrderLine");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.ShipmentTracking", b =>
                {
                    b.HasOne("Warehouse.Fulfillment.DBModel.Models.Shipment", "Shipment")
                        .WithMany("TrackingEntries")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.Carrier", b =>
                {
                    b.Navigation("ServiceLevels");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.CustomerReturn", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.Parcel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.PickList", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.SalesOrder", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Parcels");

                    b.Navigation("PickLists");
                });

            modelBuilder.Entity("Warehouse.Fulfillment.DBModel.Models.Shipment", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("TrackingEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
