using Microsoft.AspNetCore.Http;
using Warehouse.Infrastructure.Authorization;

namespace Warehouse.Fulfillment.API.Tests.Fixtures;

/// <summary>
/// Test-only <see cref="IUserPermissionService"/> that reads permissions directly from the current
/// request's JWT "permission" claims. Replaces the production cache-and-HTTP-fallback implementation
/// (introduced by CHG-ENH-004) so integration tests can drive authorization purely through tokens
/// generated by <c>CreateAuthenticatedClient</c>.
/// </summary>
public sealed class JwtClaimsUserPermissionService : IUserPermissionService
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    /// <summary>
    /// Initializes a new instance with the ASP.NET Core HTTP context accessor.
    /// </summary>
    public JwtClaimsUserPermissionService(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    /// <inheritdoc />
    public Task<IReadOnlySet<string>> GetPermissionsAsync(int userId, CancellationToken cancellationToken)
    {
        HttpContext? http = _httpContextAccessor.HttpContext;
        if (http is null)
            return Task.FromResult<IReadOnlySet<string>>(new HashSet<string>(StringComparer.Ordinal));

        IReadOnlySet<string> permissions = http.User.Claims
            .Where(c => c.Type == "permission")
            .Select(c => c.Value)
            .ToHashSet(StringComparer.Ordinal);

        return Task.FromResult(permissions);
    }
}
