<template>
  <FormWrapper v-model="visible" :mode="mode" max-width="900" :title="isEdit ? t('salesOrders.edit') : t('salesOrders.create')" :icon="isEdit ? 'mdi-file-document-edit' : 'mdi-file-document-plus'" @back="cancel">
    <v-card-title class="text-h6">
      {{ isEdit ? t('salesOrders.edit') : t('salesOrders.create') }}
    </v-card-title>

    <v-card-text>
      <v-form ref="formRef" @submit.prevent="handleSubmit">
        <v-row v-if="!isEdit" dense>
          <v-col v-bind="grid.fieldCols">
            <v-text-field
              :model-value="nextOrderNumber"
              :label="t('salesOrders.form.orderNumber')"
              prepend-inner-icon="mdi-identifier"
              :density="layout.vuetifyDensity"
              readonly
              :loading="nextOrderNumberLoading"
              :placeholder="t('salesOrders.form.orderNumberAutoGenerated')"
              persistent-placeholder
            />
          </v-col>
        </v-row>

        <v-row dense>
          <v-col v-bind="grid.fieldCols">
            <v-autocomplete
              v-model="form.customerId"
              :label="t('salesOrders.form.customer')"
              prepend-inner-icon="mdi-account"
              :density="layout.vuetifyDensity"
              :items="customers"
              item-title="name"
              item-value="id"
              :loading="customersLoading"
              :rules="[rules.requiredSelect]"
              :readonly="isEdit"
              :error-messages="fieldErrors.customerId"
              @update:model-value="onCustomerChanged"
            />
          </v-col>

          <v-col v-bind="grid.fieldCols">
            <v-select
              v-model="form.customerAccountId"
              :label="t('salesOrders.form.account')"
              prepend-inner-icon="mdi-bank"
              :density="layout.vuetifyDensity"
              :items="accounts"
              :item-title="accountItemTitle"
              item-value="id"
              :loading="accountsLoading"
              :rules="[rules.requiredSelect]"
              :readonly="isEdit"
              :disabled="!form.customerId || isEdit"
              :no-data-text="form.customerId ? t('salesOrders.form.noAccountsForCustomer') : t('salesOrders.form.selectCustomerFirst')"
              @update:model-value="onAccountChanged"
            />
          </v-col>

          <v-col v-bind="grid.fieldCols">
            <v-text-field
              :model-value="form.currencyCode"
              :label="t('salesOrders.form.currency')"
              prepend-inner-icon="mdi-currency-usd"
              :density="layout.vuetifyDensity"
              readonly
              :placeholder="t('salesOrders.form.currencyAutoFilled')"
              persistent-placeholder
            />
          </v-col>

          <v-col v-bind="grid.fieldCols">
            <v-select
              v-model="form.warehouseId"
              :label="t('salesOrders.form.warehouse')"
              prepend-inner-icon="mdi-warehouse"
              :density="layout.vuetifyDensity"
              :items="warehouses"
              item-title="name"
              item-value="id"
              :loading="warehousesLoading"
              :rules="[rules.requiredSelect]"
            />
          </v-col>

          <v-col v-bind="grid.fieldCols">
            <v-menu v-model="shipDateMenu" :close-on-content-click="false">
              <template #activator="{ props: menuProps }">
                <v-text-field
                  v-bind="menuProps"
                  :model-value="form.requestedShipDate"
                  :label="t('salesOrders.form.requestedShipDate')"
                  prepend-inner-icon="mdi-calendar"
                  :density="layout.vuetifyDensity"
                  readonly
                  clearable
                  @click:clear="form.requestedShipDate = ''"
                />
              </template>
              <v-date-picker
                :model-value="form.requestedShipDate ? new Date(form.requestedShipDate + 'T00:00:00') : undefined"
                color="primary"
                show-adjacent-months
                @update:model-value="onShipDatePicked"
              />
            </v-menu>
          </v-col>

          <v-col v-bind="grid.fieldCols">
            <v-select
              v-model="form.carrierId"
              :label="t('salesOrders.form.carrier')"
              prepend-inner-icon="mdi-truck-delivery"
              :density="layout.vuetifyDensity"
              :items="carriers"
              item-title="name"
              item-value="id"
              :loading="carriersLoading"
              clearable
              @update:model-value="onCarrierChanged"
            />
          </v-col>

          <v-col v-bind="grid.fieldCols">
            <v-select
              v-model="form.carrierServiceLevelId"
              :label="t('salesOrders.form.serviceLevel')"
              prepend-inner-icon="mdi-speedometer"
              :density="layout.vuetifyDensity"
              :items="filteredServiceLevels"
              item-title="name"
              item-value="id"
              clearable
              :disabled="!form.carrierId"
            />
          </v-col>

          <v-col v-bind="grid.fullCols">
            <v-textarea
              v-model="form.notes"
              :label="t('salesOrders.form.notes')"
              prepend-inner-icon="mdi-note-text"
              :density="layout.vuetifyDensity"
              :rules="[rules.notesLength]"
              rows="2"
              auto-grow
            />
          </v-col>
        </v-row>

        <!-- Shipping Address Section -->
        <v-divider class="my-4" />
        <div class="text-subtitle-1 font-weight-medium mb-3">{{ t('salesOrders.form.shippingAddress') }}</div>
        <v-row v-if="form.customerId" dense>
          <v-col v-bind="grid.fullCols">
            <v-select
              v-model="selectedShippingAddressId"
              :label="t('salesOrders.form.useCustomerAddress')"
              prepend-inner-icon="mdi-map-marker-multiple"
              :density="layout.vuetifyDensity"
              :items="customerAddresses"
              :item-title="shippingAddressItemTitle"
              item-value="id"
              clearable
              :no-data-text="t('salesOrders.form.noAddressesForCustomer')"
              :hint="t('salesOrders.form.useCustomerAddressHint')"
              persistent-hint
              @update:model-value="onShippingAddressPicked"
            />
          </v-col>
        </v-row>
        <v-row dense>
          <v-col v-bind="grid.fieldCols">
            <v-text-field
              v-model="form.shippingStreetLine1"
              :label="t('salesOrders.form.streetLine1')"
              :density="layout.vuetifyDensity"
              :rules="[rules.required, rules.streetLength]"
            />
          </v-col>
          <v-col v-bind="grid.fieldCols">
            <v-text-field
              v-model="form.shippingStreetLine2"
              :label="t('salesOrders.form.streetLine2')"
              :density="layout.vuetifyDensity"
              :rules="[rules.streetLength]"
            />
          </v-col>
          <v-col v-bind="grid.fullCols">
            <NomenclatureAddressFields
              v-model:country-code="form.shippingCountryCode"
              v-model:state-province="form.shippingStateProvince"
              v-model:city="form.shippingCity"
              :density="layout.vuetifyDensity"
            />
          </v-col>
          <v-col v-bind="grid.fieldCols">
            <v-text-field
              v-model="form.shippingPostalCode"
              :label="t('salesOrders.form.postalCode')"
              :density="layout.vuetifyDensity"
              :rules="[rules.required, rules.postalCodeLength]"
            />
          </v-col>
        </v-row>

        <!-- Billing Address Section -->
        <v-divider class="my-4" />
        <div class="d-flex align-center mb-3">
          <div class="text-subtitle-1 font-weight-medium">{{ t('salesOrders.form.billingAddress') }}</div>
          <v-spacer />
          <v-checkbox
            v-model="form.sameAsShipping"
            :label="t('salesOrders.form.sameAsShipping')"
            hide-details
            density="compact"
            class="mr-2"
            @update:model-value="onSameAsShippingToggled"
          />
        </div>
        <v-row v-if="!form.sameAsShipping" dense>
          <v-col v-bind="grid.fieldCols">
            <v-text-field
              v-model="form.billingStreetLine1"
              :label="t('salesOrders.form.streetLine1')"
              :density="layout.vuetifyDensity"
              :rules="[rules.required, rules.streetLength]"
            />
          </v-col>
          <v-col v-bind="grid.fieldCols">
            <v-text-field
              v-model="form.billingStreetLine2"
              :label="t('salesOrders.form.streetLine2')"
              :density="layout.vuetifyDensity"
              :rules="[rules.streetLength]"
            />
          </v-col>
          <v-col v-bind="grid.fullCols">
            <NomenclatureAddressFields
              v-model:country-code="form.billingCountryCode"
              v-model:state-province="form.billingStateProvince"
              v-model:city="form.billingCity"
              :density="layout.vuetifyDensity"
            />
          </v-col>
          <v-col v-bind="grid.fieldCols">
            <v-text-field
              v-model="form.billingPostalCode"
              :label="t('salesOrders.form.postalCode')"
              :density="layout.vuetifyDensity"
              :rules="[rules.required, rules.postalCodeLength]"
            />
          </v-col>
        </v-row>

        <!-- Lines Section (Create mode only - edit uses separate line ops) -->
        <template v-if="!isEdit">
          <v-divider class="my-4" />
          <div class="d-flex align-center mb-2">
            <div class="text-subtitle-1 font-weight-medium">{{ t('salesOrders.detail.lines') }}</div>
            <v-spacer />
            <div v-if="form.lines.length > 0" class="text-subtitle-2 font-weight-medium mr-4">
              {{ t('salesOrders.form.grandTotal') }}: {{ grandTotal.toFixed(2) }}
            </div>
            <v-btn size="small" color="primary" variant="tonal" prepend-icon="mdi-plus" @click="addLine">
              {{ t('common.create') }}
            </v-btn>
          </div>

          <v-table :density="layout.vuetifyDensity">
            <thead>
              <tr>
                <th>{{ t('salesOrders.lines.product') }}</th>
                <th>{{ t('salesOrders.lines.orderedQty') }}</th>
                <th>{{ t('salesOrders.lines.unitPrice') }}</th>
                <th>{{ t('salesOrders.lines.lineTotal') }}</th>
                <th>{{ t('salesOrders.lines.notes') }}</th>
                <th style="width: 60px"></th>
              </tr>
            </thead>
            <tbody>
              <tr v-if="form.lines.length === 0">
                <td colspan="6" class="text-center text-medium-emphasis py-4">
                  {{ t('salesOrders.detail.noLines') }}
                </td>
              </tr>
              <tr v-for="(line, idx) in form.lines" :key="idx">
                <td style="min-width: 200px">
                  <v-autocomplete
                    v-model="line.productId"
                    :items="products"
                    item-title="name"
                    item-value="id"
                    :density="layout.vuetifyDensity"
                    hide-details
                    variant="underlined"
                    :loading="productsLoading"
                  />
                </td>
                <td style="min-width: 100px">
                  <v-text-field
                    v-model.number="line.orderedQuantity"
                    type="number"
                    :density="layout.vuetifyDensity"
                    hide-details
                    variant="underlined"
                    :min="0.01"
                    step="any"
                  />
                </td>
                <td style="min-width: 100px">
                  <v-text-field
                    v-model.number="line.unitPrice"
                    type="number"
                    :density="layout.vuetifyDensity"
                    hide-details
                    variant="underlined"
                    :min="0"
                    step="any"
                  />
                </td>
                <td class="text-right" style="min-width: 80px">
                  {{ ((line.orderedQuantity || 0) * (line.unitPrice || 0)).toFixed(2) }}
                </td>
                <td style="min-width: 120px">
                  <v-text-field
                    v-model="line.notes"
                    :density="layout.vuetifyDensity"
                    hide-details
                    variant="underlined"
                  />
                </td>
                <td>
                  <v-btn icon="mdi-delete" size="small" variant="text" color="error" @click="removeLine(idx)" />
                </td>
              </tr>
            </tbody>
          </v-table>
        </template>
      </v-form>
    </v-card-text>

    <v-card-actions>
      <v-spacer />
      <v-btn variant="text" @click="cancel">{{ t('common.cancel') }}</v-btn>
      <v-btn color="primary" variant="flat" :loading="loading" @click="handleSubmit">
        {{ t('common.save') }}
      </v-btn>
    </v-card-actions>
  </FormWrapper>
</template>

<script setup lang="ts">
import { ref, reactive, computed, watch, onMounted } from 'vue';
import { useI18n } from 'vue-i18n';
import { useNotificationStore } from '@shared/stores/notification';
import { useLayoutStore } from '@shared/stores/layout';
import { useFormGrid } from '@shared/composables/useFormGrid';
import { getApiErrorMessage } from '@shared/utils/getApiErrorMessage';
import FormWrapper from '@shared/components/molecules/FormWrapper.vue';
import NomenclatureAddressFields from '@shared/components/molecules/NomenclatureAddressFields.vue';
import {
  createSalesOrder,
  updateSalesOrder,
  getSalesOrderById,
  getNextSalesOrderNumber,
} from '@features/fulfillment/api/sales-orders';
import { searchCarriers, getCarrierById } from '@features/fulfillment/api/carriers';
import { searchCustomers, getCustomerById } from '@features/customers/api/customers';
import { searchProducts } from '@features/inventory/api/products';
import { searchWarehouses } from '@features/inventory/api/warehouses';
import type { CustomerDto, CustomerAccountDto, CustomerAddressDto } from '@features/customers/types/customer';
import type { ProductDto, WarehouseDto } from '@features/inventory/types/inventory';
import type { CarrierDto, CarrierServiceLevelDto, SalesOrderDetailDto } from '@features/fulfillment/types/fulfillment';
import type { AxiosError } from 'axios';
import type { ProblemDetails } from '@shared/types/api';

interface OrderLineForm {
  productId: number | null;
  orderedQuantity: number;
  unitPrice: number;
  notes: string;
}

const { t } = useI18n();
const notification = useNotificationStore();
const layout = useLayoutStore();
const grid = useFormGrid();

const visible = defineModel<boolean>({ required: true });

const props = defineProps<{
  soId?: number | null;
  mode?: 'dialog' | 'page';
}>();

const emit = defineEmits<{
  saved: [];
  cancelled: [];
}>();

const isEdit = ref(false);
const formRef = ref();
const loading = ref(false);
const customers = ref<CustomerDto[]>([]);
const customersLoading = ref(false);
const warehouses = ref<WarehouseDto[]>([]);
const warehousesLoading = ref(false);
const products = ref<ProductDto[]>([]);
const productsLoading = ref(false);
const carriers = ref<CarrierDto[]>([]);
const carriersLoading = ref(false);
const allServiceLevels = ref<CarrierServiceLevelDto[]>([]);
const accounts = ref<CustomerAccountDto[]>([]);
const accountsLoading = ref(false);
const customerAddresses = ref<CustomerAddressDto[]>([]);
const selectedShippingAddressId = ref<number | null>(null);
const nextOrderNumber = ref('');
const nextOrderNumberLoading = ref(false);

const shipDateMenu = ref(false);

const fieldErrors = reactive<Record<string, string[]>>({
  customerId: [],
});

const form = reactive({
  customerId: null as number | null,
  customerAccountId: null as number | null,
  currencyCode: '',
  warehouseId: null as number | null,
  requestedShipDate: '',
  carrierId: null as number | null,
  carrierServiceLevelId: null as number | null,
  shippingStreetLine1: '',
  shippingStreetLine2: '',
  shippingCity: '',
  shippingStateProvince: '',
  shippingPostalCode: '',
  shippingCountryCode: '',
  billingStreetLine1: '',
  billingStreetLine2: '',
  billingCity: '',
  billingStateProvince: '',
  billingPostalCode: '',
  billingCountryCode: '',
  sameAsShipping: true,
  notes: '',
  lines: [] as OrderLineForm[],
});

function accountItemTitle(account: CustomerAccountDto): string {
  return account.description
    ? `${account.currencyCode} - ${account.description}`
    : account.currencyCode;
}

async function loadCustomerData(customerId: number): Promise<void> {
  accountsLoading.value = true;
  try {
    const detail = await getCustomerById(customerId);
    accounts.value = detail.accounts ?? [];
    const primary = accounts.value.find((a) => a.isPrimary);
    const auto = primary ?? (accounts.value.length === 1 ? accounts.value[0] : null);
    if (auto) {
      form.customerAccountId = auto.id;
      form.currencyCode = auto.currencyCode;
    } else {
      form.customerAccountId = null;
      form.currencyCode = '';
    }
    customerAddresses.value = detail.addresses ?? [];
    const shippable = customerAddresses.value.filter(
      (a) => a.addressType === 'Shipping' || a.addressType === 'Both',
    );
    const defaultShip = shippable.find((a) => a.isDefault)
      ?? (shippable.length === 1 ? shippable[0] : null);
    if (defaultShip) {
      applyAddressToShipping(defaultShip);
    }
  } catch {
    accounts.value = [];
    form.customerAccountId = null;
    form.currencyCode = '';
    customerAddresses.value = [];
    selectedShippingAddressId.value = null;
  } finally {
    accountsLoading.value = false;
  }
}

function applyAddressToShipping(address: CustomerAddressDto): void {
  selectedShippingAddressId.value = address.id;
  form.shippingStreetLine1 = address.streetLine1;
  form.shippingStreetLine2 = address.streetLine2 ?? '';
  form.shippingCity = address.city;
  form.shippingStateProvince = address.stateProvince ?? '';
  form.shippingPostalCode = address.postalCode;
  form.shippingCountryCode = address.countryCode;
}

function shippingAddressItemTitle(address: CustomerAddressDto): string {
  const parts: string[] = [address.streetLine1];
  if (address.streetLine2) parts.push(address.streetLine2);
  parts.push(address.city);
  if (address.stateProvince) parts.push(address.stateProvince);
  parts.push(`${address.countryCode} ${address.postalCode}`);
  const suffix: string = address.isDefault ? ` (${address.addressType} ★)` : ` (${address.addressType})`;
  return parts.join(', ') + suffix;
}

function onShippingAddressPicked(value: number | null): void {
  if (value === null) return;
  const picked = customerAddresses.value.find((a) => a.id === value);
  if (picked) {
    applyAddressToShipping(picked);
  }
}

function onCustomerChanged(value: number | null): void {
  fieldErrors.customerId = [];
  form.customerAccountId = null;
  form.currencyCode = '';
  accounts.value = [];
  customerAddresses.value = [];
  selectedShippingAddressId.value = null;
  if (value) {
    loadCustomerData(value);
  }
}

function onAccountChanged(value: number | null): void {
  if (value === null) {
    form.currencyCode = '';
    return;
  }
  const selected = accounts.value.find((a) => a.id === value);
  form.currencyCode = selected ? selected.currencyCode : '';
}

function copyShippingToBilling(): void {
  form.billingStreetLine1 = form.shippingStreetLine1;
  form.billingStreetLine2 = form.shippingStreetLine2;
  form.billingCity = form.shippingCity;
  form.billingStateProvince = form.shippingStateProvince;
  form.billingPostalCode = form.shippingPostalCode;
  form.billingCountryCode = form.shippingCountryCode;
}

function onSameAsShippingToggled(value: boolean | null): void {
  if (value === true) {
    copyShippingToBilling();
  }
}

function isSameAddress(detail: SalesOrderDetailDto): boolean {
  return detail.billingStreetLine1 === detail.shippingStreetLine1
    && (detail.billingStreetLine2 ?? '') === (detail.shippingStreetLine2 ?? '')
    && detail.billingCity === detail.shippingCity
    && (detail.billingStateProvince ?? '') === (detail.shippingStateProvince ?? '')
    && detail.billingPostalCode === detail.shippingPostalCode
    && detail.billingCountryCode === detail.shippingCountryCode;
}

const filteredServiceLevels = computed(() => {
  return allServiceLevels.value;
});

const grandTotal = computed(() => {
  return form.lines.reduce((sum, line) => sum + (line.orderedQuantity || 0) * (line.unitPrice || 0), 0);
});

async function loadDropdowns(): Promise<void> {
  customersLoading.value = true;
  warehousesLoading.value = true;
  productsLoading.value = true;
  carriersLoading.value = true;
  const results = await Promise.allSettled([
    searchCustomers({ includeDeleted: false, sortDescending: false, page: 1, pageSize: 100 }),
    searchWarehouses({ includeDeleted: false, sortDescending: false, page: 1, pageSize: 100 }),
    searchProducts({ includeDeleted: false, sortDescending: false, page: 1, pageSize: 100 }),
    searchCarriers({ isActive: true, sortDescending: false, page: 1, pageSize: 100 }),
  ]);
  if (results[0].status === 'fulfilled') customers.value = results[0].value.items;
  if (results[1].status === 'fulfilled') warehouses.value = results[1].value.items;
  if (results[2].status === 'fulfilled') products.value = results[2].value.items;
  if (results[3].status === 'fulfilled') carriers.value = results[3].value.items;
  customersLoading.value = false;
  warehousesLoading.value = false;
  productsLoading.value = false;
  carriersLoading.value = false;
}

async function loadNextOrderNumber(): Promise<void> {
  nextOrderNumberLoading.value = true;
  try {
    nextOrderNumber.value = await getNextSalesOrderNumber();
  } catch {
    nextOrderNumber.value = '';
  } finally {
    nextOrderNumberLoading.value = false;
  }
}

onMounted(() => loadDropdowns());

async function onCarrierChanged(): Promise<void> {
  form.carrierServiceLevelId = null;
  allServiceLevels.value = [];
  if (!form.carrierId) return;
  try {
    const detail = await getCarrierById(form.carrierId);
    allServiceLevels.value = detail.serviceLevels;
  } catch {
    allServiceLevels.value = [];
  }
}

async function populateForm(): Promise<void> {
  if (visible.value && props.soId) {
    isEdit.value = true;
    try {
      const detail: SalesOrderDetailDto = await getSalesOrderById(props.soId);
      form.customerId = detail.customerId;
      form.customerAccountId = detail.customerAccountId ?? null;
      form.currencyCode = detail.currencyCode ?? '';
      form.warehouseId = detail.warehouseId;
      form.requestedShipDate = detail.requestedShipDate ? detail.requestedShipDate.substring(0, 10) : '';
      form.carrierId = detail.carrierId;
      form.carrierServiceLevelId = detail.carrierServiceLevelId;
      form.shippingStreetLine1 = detail.shippingStreetLine1;
      form.shippingStreetLine2 = detail.shippingStreetLine2 ?? '';
      form.shippingCity = detail.shippingCity;
      form.shippingStateProvince = detail.shippingStateProvince ?? '';
      form.shippingPostalCode = detail.shippingPostalCode;
      form.shippingCountryCode = detail.shippingCountryCode;
      form.billingStreetLine1 = detail.billingStreetLine1 ?? '';
      form.billingStreetLine2 = detail.billingStreetLine2 ?? '';
      form.billingCity = detail.billingCity ?? '';
      form.billingStateProvince = detail.billingStateProvince ?? '';
      form.billingPostalCode = detail.billingPostalCode ?? '';
      form.billingCountryCode = detail.billingCountryCode ?? '';
      form.sameAsShipping = isSameAddress(detail);
      form.notes = detail.notes ?? '';
      form.lines = [];
      if (detail.customerId) {
        try {
          const customerDetail = await getCustomerById(detail.customerId);
          accounts.value = customerDetail.accounts ?? [];
          customerAddresses.value = customerDetail.addresses ?? [];
        } catch {
          accounts.value = [];
          customerAddresses.value = [];
        }
      }
      selectedShippingAddressId.value = null;
      if (detail.carrierId) {
        try {
          const carrierDetail = await getCarrierById(detail.carrierId);
          allServiceLevels.value = carrierDetail.serviceLevels;
        } catch {
          allServiceLevels.value = [];
        }
      }
    } catch (err) {
      notification.error(getApiErrorMessage(err, t));
    }
  } else if (visible.value) {
    isEdit.value = false;
    form.customerId = null;
    form.customerAccountId = null;
    form.currencyCode = '';
    form.warehouseId = null;
    form.requestedShipDate = '';
    form.carrierId = null;
    form.carrierServiceLevelId = null;
    form.shippingStreetLine1 = '';
    form.shippingStreetLine2 = '';
    form.shippingCity = '';
    form.shippingStateProvince = '';
    form.shippingPostalCode = '';
    form.shippingCountryCode = '';
    form.billingStreetLine1 = '';
    form.billingStreetLine2 = '';
    form.billingCity = '';
    form.billingStateProvince = '';
    form.billingPostalCode = '';
    form.billingCountryCode = '';
    form.sameAsShipping = true;
    form.notes = '';
    form.lines = [];
    allServiceLevels.value = [];
    accounts.value = [];
    customerAddresses.value = [];
    selectedShippingAddressId.value = null;
    loadNextOrderNumber();
  }
  fieldErrors.customerId = [];
}

watch(visible, populateForm, { immediate: true });
watch(() => props.soId, populateForm);

function addLine(): void {
  form.lines.push({ productId: null, orderedQuantity: 1, unitPrice: 0, notes: '' });
}

function removeLine(index: number): void {
  form.lines.splice(index, 1);
}

function onShipDatePicked(value: unknown): void {
  if (value instanceof Date) {
    const y = value.getFullYear();
    const m = String(value.getMonth() + 1).padStart(2, '0');
    const d = String(value.getDate()).padStart(2, '0');
    form.requestedShipDate = `${y}-${m}-${d}`;
  } else {
    form.requestedShipDate = '';
  }
  shipDateMenu.value = false;
}

const rules = {
  required: (v: string) => !!v || t('common.required'),
  requiredSelect: (v: number | null) => v !== null || t('common.required'),
  notesLength: (v: string) => !v || v.length <= 2000 || t('validation.notesLength'),
  streetLength: (v: string) => !v || v.length <= 200 || t('validation.streetLength'),
  postalCodeLength: (v: string) => !v || v.length <= 20 || t('validation.postalCodeLength'),
};

async function handleSubmit(): Promise<void> {
  const { valid } = await formRef.value.validate();
  if (!valid) return;

  if (!isEdit.value && form.lines.length === 0) {
    notification.error(t('salesOrders.detail.noLines'));
    return;
  }

  if (!isEdit.value) {
    const invalidLines = form.lines.some(
      (l) => !l.productId || !l.orderedQuantity || l.orderedQuantity <= 0 || l.unitPrice < 0,
    );
    if (invalidLines) {
      notification.error(t('errors.VALIDATION_ERROR'));
      return;
    }
  }

  if (form.sameAsShipping) copyShippingToBilling();

  loading.value = true;
  try {
    if (isEdit.value && props.soId) {
      await updateSalesOrder(props.soId, {
        warehouseId: form.warehouseId!,
        requestedShipDate: form.requestedShipDate || null,
        carrierId: form.carrierId,
        carrierServiceLevelId: form.carrierServiceLevelId,
        shippingStreetLine1: form.shippingStreetLine1,
        shippingStreetLine2: form.shippingStreetLine2 || null,
        shippingCity: form.shippingCity,
        shippingStateProvince: form.shippingStateProvince || null,
        shippingPostalCode: form.shippingPostalCode,
        shippingCountryCode: form.shippingCountryCode,
        billingStreetLine1: form.billingStreetLine1,
        billingStreetLine2: form.billingStreetLine2 || null,
        billingCity: form.billingCity,
        billingStateProvince: form.billingStateProvince || null,
        billingPostalCode: form.billingPostalCode,
        billingCountryCode: form.billingCountryCode,
        notes: form.notes || null,
      });
      notification.success(t('salesOrders.edit') + ' \u2713');
    } else {
      await createSalesOrder({
        customerId: form.customerId!,
        customerAccountId: form.customerAccountId!,
        currencyCode: form.currencyCode,
        warehouseId: form.warehouseId!,
        requestedShipDate: form.requestedShipDate || null,
        carrierId: form.carrierId,
        carrierServiceLevelId: form.carrierServiceLevelId,
        shippingStreetLine1: form.shippingStreetLine1,
        shippingStreetLine2: form.shippingStreetLine2 || null,
        shippingCity: form.shippingCity,
        shippingStateProvince: form.shippingStateProvince || null,
        shippingPostalCode: form.shippingPostalCode,
        shippingCountryCode: form.shippingCountryCode,
        billingStreetLine1: form.billingStreetLine1,
        billingStreetLine2: form.billingStreetLine2 || null,
        billingCity: form.billingCity,
        billingStateProvince: form.billingStateProvince || null,
        billingPostalCode: form.billingPostalCode,
        billingCountryCode: form.billingCountryCode,
        notes: form.notes || null,
        lines: form.lines.map((l) => ({
          productId: l.productId!,
          orderedQuantity: l.orderedQuantity,
          unitPrice: l.unitPrice,
          notes: l.notes || null,
        })),
      });
      notification.success(t('salesOrders.create') + ' \u2713');
    }
    visible.value = false;
    emit('saved');
  } catch (err) {
    handleApiError(err as AxiosError<ProblemDetails>);
  } finally {
    loading.value = false;
  }
}

function handleApiError(err: AxiosError<ProblemDetails>): void {
  const errorCode = err.response?.data?.title;
  if (errorCode === 'CUSTOMER_NOT_FOUND') {
    fieldErrors.customerId = [err.response?.data?.detail || t('errors.CUSTOMER_NOT_FOUND')];
  } else {
    notification.error(getApiErrorMessage(err, t));
  }
}

function cancel(): void {
  visible.value = false;
  emit('cancelled');
}
</script>
