// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse.Inventory.DBModel;

#nullable disable

namespace Warehouse.Inventory.DBModel.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260408223933_RemoveWarehouseIsActiveColumn")]
    partial class RemoveWarehouseIsActiveColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly?>("ManufacturingDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_Batches_ExpiryDate")
                        .HasFilter("[ExpiryDate] IS NOT NULL");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Batches_ProductId");

                    b.HasIndex("ProductId", "BatchNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Batches_ProductId_BatchNumber");

                    b.ToTable("Batches", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.BillOfMaterials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ParentProductId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ParentProductId" }, "IX_BillOfMaterials_ParentProductId");

                    b.ToTable("BillOfMaterials", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.BomLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillOfMaterialsId")
                        .HasColumnType("int");

                    b.Property<int>("ChildProductId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BillOfMaterialsId", "ChildProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_BomLines_BomId_ChildProductId");

                    b.HasIndex(new[] { "BillOfMaterialsId" }, "IX_BomLines_BillOfMaterialsId");

                    b.HasIndex(new[] { "ChildProductId" }, "IX_BomLines_ChildProductId");

                    b.ToTable("BomLines", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.InventoryAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppliedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("AppliedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("RejectedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SourceStocktakeSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_InventoryAdjustments_CreatedAtUtc");

                    b.HasIndex("SourceStocktakeSessionId")
                        .HasDatabaseName("IX_InventoryAdjustments_SourceStocktakeSessionId")
                        .HasFilter("[SourceStocktakeSessionId] IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_InventoryAdjustments_Status");

                    b.ToTable("InventoryAdjustments", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.InventoryAdjustmentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("AdjustmentId")
                        .HasColumnType("int");

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExpectedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdjustmentId")
                        .HasDatabaseName("IX_InventoryAdjustmentLines_AdjustmentId");

                    b.HasIndex("BatchId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryAdjustmentLines", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("RequiresBatchTracking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("IX_Products_Barcode")
                        .HasFilter("[Barcode] IS NOT NULL");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Products_IsDeleted")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Sku")
                        .HasDatabaseName("IX_Products_Sku")
                        .HasFilter("[Sku] IS NOT NULL");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Products_CategoryId");

                    b.HasIndex(new[] { "Code" }, "IX_Products_Code")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "IX_Products_Name");

                    b.HasIndex(new[] { "UnitOfMeasureId" }, "IX_Products_UnitOfMeasureId");

                    b.ToTable("Products", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.ProductAccessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessoryProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryProductId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_ProductAccessories_ProductId");

                    b.HasIndex("ProductId", "AccessoryProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductAccessories_ProductId_AccessoryProductId");

                    b.ToTable("ProductAccessories", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_ProductCategories_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "ParentCategoryId" }, "IX_ProductCategories_ParentCategoryId");

                    b.ToTable("ProductCategories", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.ProductSubstitute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SubstituteProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_ProductSubstitutes_ProductId");

                    b.HasIndex("SubstituteProductId");

                    b.HasIndex("ProductId", "SubstituteProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductSubstitutes_ProductId_SubstituteProductId");

                    b.ToTable("ProductSubstitutes", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.StockLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityOnHand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("QuantityReserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("IX_StockLevels_LocationId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_StockLevels_ProductId");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_StockLevels_WarehouseId");

                    b.ToTable("StockLevels", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_StockMovements_CreatedAtUtc");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_StockMovements_ProductId");

                    b.HasIndex("ReasonCode")
                        .HasDatabaseName("IX_StockMovements_ReasonCode");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_StockMovements_WarehouseId");

                    b.ToTable("StockMovements", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.StocktakeCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("CountedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("CountedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExpectedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Variance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_StocktakeCounts_ProductId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_StocktakeCounts_SessionId");

                    b.HasIndex("SessionId", "ProductId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("IX_StocktakeCounts_SessionId_ProductId_LocationId")
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.ToTable("StocktakeCounts", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.StocktakeSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("CompletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_StocktakeSessions_CreatedAtUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_StocktakeSessions_Status");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_StocktakeSessions_WarehouseId");

                    b.HasIndex("ZoneId");

                    b.ToTable("StocktakeSessions", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.StorageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Capacity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_StorageLocations_WarehouseId");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("IX_StorageLocations_ZoneId");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_StorageLocations_WarehouseId_Code");

                    b.ToTable("StorageLocations", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code" }, "IX_UnitsOfMeasure_Code")
                        .IsUnique();

                    b.ToTable("UnitsOfMeasure", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.WarehouseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Warehouses_IsDeleted")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex(new[] { "Code" }, "IX_Warehouses_Code")
                        .IsUnique();

                    b.ToTable("Warehouses", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.WarehouseTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("CompletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationWarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("SourceWarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.HasKey("Id");

                    b.HasIndex("DestinationWarehouseId")
                        .HasDatabaseName("IX_WarehouseTransfers_DestinationWarehouseId");

                    b.HasIndex("SourceWarehouseId")
                        .HasDatabaseName("IX_WarehouseTransfers_SourceWarehouseId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WarehouseTransfers_Status");

                    b.ToTable("WarehouseTransfers", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.WarehouseTransferLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DestinationLocationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SourceLocationId")
                        .HasColumnType("int");

                    b.Property<int>("TransferId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SourceLocationId");

                    b.HasIndex("TransferId")
                        .HasDatabaseName("IX_WarehouseTransferLines_TransferId");

                    b.ToTable("WarehouseTransferLines", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_Zones_WarehouseId");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Zones_WarehouseId_Code");

                    b.ToTable("Zones", "inventory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.Batch", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.BillOfMaterials", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.Product", "ParentProduct")
                        .WithMany()
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentProduct");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.BomLine", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.BillOfMaterials", "BillOfMaterials")
                        .WithMany("Lines")
                        .HasForeignKey("BillOfMaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Inventory.DBModel.Models.Product", "ChildProduct")
                        .WithMany()
                        .HasForeignKey("ChildProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BillOfMaterials");

                    b.Navigation("ChildProduct");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.InventoryAdjustment", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.StocktakeSession", "SourceStocktakeSession")
                        .WithMany()
                        .HasForeignKey("SourceStocktakeSessionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("SourceStocktakeSession");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.InventoryAdjustmentLine", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.InventoryAdjustment", "Adjustment")
                        .WithMany("Lines")
                        .HasForeignKey("AdjustmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Inventory.DBModel.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Inventory.DBModel.Models.StorageLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Inventory.DBModel.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Inventory.DBModel.Models.WarehouseEntity", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Adjustment");

                    b.Navigation("Batch");

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.Product", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Warehouse.Inventory.DBModel.Models.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("Products")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.ProductAccessory", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.Product", "AccessoryProduct")
                        .WithMany()
                        .HasForeignKey("AccessoryProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Inventory.DBModel.Models.Product", "Product")
                        .WithMany("Accessories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessoryProduct");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.ProductCategory", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.ProductCategory", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.ProductSubstitute", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.Product", "Product")
                        .WithMany("Substitutes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Inventory.DBModel.Models.Product", "SubstituteProduct")
                        .WithMany()
                        .HasForeignKey("SubstituteProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SubstituteProduct");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.StockLevel", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Inventory.DBModel.Models.StorageLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Inventory.DBModel.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Inventory.DBModel.Models.WarehouseEntity", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.StockMovement", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Inventory.DBModel.Models.StorageLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Inventory.DBModel.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Inventory.DBModel.Models.WarehouseEntity", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.StocktakeCount", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.StorageLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Inventory.DBModel.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Inventory.DBModel.Models.StocktakeSession", "Session")
                        .WithMany("Counts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.StocktakeSession", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.WarehouseEntity", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Inventory.DBModel.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Warehouse");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.StorageLocation", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.WarehouseEntity", "Warehouse")
                        .WithMany("Locations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Inventory.DBModel.Models.Zone", "Zone")
                        .WithMany("Locations")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Warehouse");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.WarehouseTransfer", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.WarehouseEntity", "DestinationWarehouse")
                        .WithMany()
                        .HasForeignKey("DestinationWarehouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Inventory.DBModel.Models.WarehouseEntity", "SourceWarehouse")
                        .WithMany()
                        .HasForeignKey("SourceWarehouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DestinationWarehouse");

                    b.Navigation("SourceWarehouse");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.WarehouseTransferLine", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.StorageLocation", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Inventory.DBModel.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Inventory.DBModel.Models.StorageLocation", "SourceLocation")
                        .WithMany()
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Inventory.DBModel.Models.WarehouseTransfer", "Transfer")
                        .WithMany("Lines")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationLocation");

                    b.Navigation("Product");

                    b.Navigation("SourceLocation");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.Zone", b =>
                {
                    b.HasOne("Warehouse.Inventory.DBModel.Models.WarehouseEntity", "Warehouse")
                        .WithMany("Zones")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.BillOfMaterials", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.InventoryAdjustment", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.Product", b =>
                {
                    b.Navigation("Accessories");

                    b.Navigation("Substitutes");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.ProductCategory", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.StocktakeSession", b =>
                {
                    b.Navigation("Counts");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.UnitOfMeasure", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.WarehouseEntity", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.WarehouseTransfer", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Warehouse.Inventory.DBModel.Models.Zone", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
